[package]
name = "double-pendulum-classifier"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
anyhow = "1"
criterion = "0.8"
diffsol = { version = "0.16", default-features = false, features = ["nalgebra"] }
ode_solvers = "0.6"
peroxide = { version = "0.43", default-features = false }

[[bench]]
name = "compare"
harness = false
